---
# --- AAP credentials ---
controller_credentials:
  # SSH credential for connecting to managed web server hosts
  - name: "{{ machine_host_credential_name }}"
    organization: "{{ demo_organization_name }}"
    credential_type: Machine
    inputs:
      username: "{{ machine_ssh_user }}"
      ssh_key_data: "{{ machine_ssh_key }}"
    state: present

  # Controller API token for EDA to trigger job templates
  - name: "{{ demo_controller_token_name }}"
    organization: "{{ demo_organization_name }}"
    credential_type: "Red Hat Ansible Automation Platform"
    inputs:
      host: "https://{{ aap_hostname }}"
      username: "{{ aap_username }}"
      password: "{{ aap_password }}"
      verify_ssl: "{{ aap_validate_certs }}"
    state: present
