---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "--pre"

images:
  base_image:
    name: "registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest"

dependencies:
  python:
    - requirements.txt
  galaxy:
    - requirements.yml

additional_build_steps:
  append_final:
    - COPY files/ /opt/aiops/files/
